### PR TITLE
fixed create.sh script so it can run on OSX

### PR DESCRIPTION
**Pull request by royra**

### CODE REVIEW

**Comment by IsraeliUser** [comment]
@royra 
OK?

**Comment by royra** [comment]
The cost of duplicating the script will be in porting future changes to its sibling. Do you think it's worth it for this tiny difference?

**Comment by IsraeliUser** [comment]
Does removing the ` --suffix=.txt` affects Linux users?
If the answers in "No", I will merge your request and remove the new file.

**Comment by royra** [comment]
No. It's giving a prettier name to a file that's being renamed milliseconds later.

**Comment by IsraeliUser** [comment]
Fixed.

**Pull request merged**
