### PR TITLE
Auto Checksum

### PR DESCRIPTION
**Pull request by tzagim**
Automatically adding Checksum to the file without having to do it locally

A demo is at [main branch](https://github.com/tzagim/EasyListHebrew/tree/main)

### CODE REVIEW

**Comment by EasyListHebrew** [comment]
@tzagim thank you very much for the contribution this will make life easier.

**Comment by Hebrew-uBO-User** [comment]
@tzagim 
Mereged.
Thank you!
Can you adjust this script so it will make a new comment only if the checksum is wrong. We have `validateChecksum.py`.

**Comment by tzagim** [comment]
@Hebrew-uBO-User 
I didn't delve into what each file does.
Are you interested in running the file  `validateChecksum.py` if the result is not equal to "Checksum is valid" then run `addChecksum.py`?

**Comment by Hebrew-uBO-User** [comment]
@tzagim 
Yes.
I mean, if the checksum is valid, the bot will not create a commit.

**Comment by tzagim** [comment]
@Hebrew-uBO-User 
Sorry for the late reply, days are a bit busy.

Without delving into the code, if we use the existing test logic, then the test method is:

```
      - name: Validate Checksum
        id: checksum_validation
        run: |
          python3 .github/scripts/validateChecksum.py EasyListHebrew.txt
          if [ $? == 0 ] ; then
            echo "build=yes" >> $GITHUB_ENV
          else
            echo "build=no" >> $GITHUB_ENV
            echo 'something wrong'
            exit 0
          fi

      - name: Run the script
        if: env.build == 'yes'
        run: |
          tmpList=$(mktemp)
          python3 .github/scripts/addChecksum.py EasyListHebrew.txt $tmpList
          output=$(python3 .github/scripts/validateChecksum.py $tmpList)
          echo "Validation output for new file: $output"
          if [[ $output == "Checksum is valid" ]]; then
            mv -f $tmpList EasyListHebrew.txt
          else
            echo 'Something went wrong with checksum validation for the updated file.'
            exit 1
          fi
          python3 .github/scripts/genhosts.py EasyListHebrew.txt

      - name: Ensure EasyListHebrew.txt exists
        if: env.build == 'yes'
        run: |
          if [ ! -f EasyListHebrew.txt ]; then
            echo "Creating EasyListHebrew.txt"
            touch EasyListHebrew.txt
          fi

      - name: Update EasyListHebrew.txt file
        if: env.build == 'yes'
        run: |
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git add EasyListHebrew.txt
            git commit -m "Update Checksum"
            git push
```

I tried to run this test, there is an error in the test file it always returns a wrong result, maybe it is checking according to the current time?

**Comment by Hebrew-uBO-User** [comment]
@tzagim 
Maybe it's the encoding.
Try to use UTF-8 with LF Unix end of line sequence.

**Comment by tzagim** [comment]
@Hebrew-uBO-User

It seems to be in the correct encoding ([here](https://github.com/easylist/EasyListHebrew/blob/e734e6542d8607626edecbb5bf729ab25ec20d1a/.github/scripts/validateChecksum.py#L58))

Let's try debugging, if you run localy `validateChecksum.py` repeatedly, what result do you get?

**Pull request merged**
