### PR TITLE
Another fix for kikar.co.il

### PR DESCRIPTION
**Pull request by tzagim**
Completion for fix for https://github.com/easylist/EasyListHebrew/pull/421

Should totally fix https://github.com/easylist/EasyListHebrew/issues/420

### CODE REVIEW

**Comment by Halbour** [comment]
Well... I still have it even after force-updating again (it wasn't, but it's back now :( )
image

**Comment by tzagim** [comment]
@Halbour 
It hasn't merged yet...

**Comment by Hebrew-uBO-User** [comment]
Fixed.

@Halbour
Update your filters again.

**Comment by Halbour** [comment]
Works so much cleaner now (as something with uBO should, lol). Thank you!


> @Halbour It hasn't merged yet...

I... don't really know how GitHub works, TBH

**Pull request merged**
