### PR TITLE
Block rotter inline ads

### PR DESCRIPTION
**Pull request by yuvadm**

### CODE REVIEW

**Comment by EasyListHebrew** [comment]
Hey @yuvadm thanks for the PR, can you please attach a photo of what is been blocked?

**Comment by yuvadm** [comment]
Inline ads on this page - https://rotter.net/forum/listforum.php

I should have probably changed the filter for that page only now that I think of it.

**Comment by Hebrew-uBO-User** [comment]
@yuvadm 

Please test
`rotter.net##[href^="https://bit.ly/"] > b`

**Comment by yuvadm** [comment]
@Hebrew-uBO-User nope, it doens't have the same effect, doesn't cover the inline ads

**Comment by Hebrew-uBO-User** [comment]
@yuvadm 
Your solution does not work on my end.
Please specify your adblocker and browser.

Now I see that the inline ads do not always link to BitLy...
So my suggestion won't work in some cases.

**Comment by yuvadm** [comment]
ublock origin on FF

**Comment by Hebrew-uBO-User** [comment]
@yuvadm 
My mistake.

`rotter.net##td:matches-attr(colspan=3):upward(1)` hides inline ads on 
`https://rotter.net/forum/listforum.php`

and `rotter.net##[href^="https://bit.ly/"] > b` hides inline ads on 
`https://rotter.net/cgi-bin/forum/dcboard.cgi?az=list&forum=scoops1`

However, I suspect these filters may break other pages on this site.

**Comment by jbkkd** [comment]
I got to `rotter.net##tr:nth-of-type(6)` as a solution that works here. Tested on Firefox with uBlock Origin

**Pull request closed without merging**
